#!/bin/sh
XML=$1
INC=$2
( [ -z ${XML} ] || [ -z ${INC} ] ) && echo "Invalid parameters to mkaddrspace" && exit 1
( [ -z ${S2OPC_ROOT} ] ) && echo "S2OPC_ROOT variable is not set" && exit 1
( ! [ -e ${S2OPC_ROOT}/scripts/generate-s2opc-address-space.py ] ) && echo "S2OPC not installed as expected in ${S2OPC_ROOT}/.." && exit 1

echo "python3 ${S2OPC_ROOT}/../S2OPC/scripts/generate-s2opc-address-space.py ${XML} ${INC}" &>2
python3 ${S2OPC_ROOT}/scripts/generate-s2opc-address-space.py ${XML} ${INC} || exit $?
